"""use json for test cases

Revision ID: 90be3fa1646d
Revises: 
Create Date: 2026-08-15 16:55:49.694797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90be3fa1646d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()

    # Convert existing text data into valid JSON strings
    bind.exec_driver_sql("""
        UPDATE test_cases
        SET input_data = CASE id
            WHEN 1 THEN '{"nums":[2,7,11,15],"target":9}'
            WHEN 2 THEN '{"nums":[3,2,4],"target":6}'
            WHEN 3 THEN '{"nums":[1,2,3,4,5],"target":4}'
            WHEN 4 THEN '{"nums":[1,3,5,7],"target":6}'
            WHEN 5 THEN '{"s":"()[]{}"}'
            WHEN 6 THEN '{"s":"([)]"}'
            WHEN 7 THEN '{"intervals":[[1,3],[2,6],[8,10],[9,12]]}'
        END
    """)

    bind.exec_driver_sql("""
        UPDATE test_cases
        SET expected_output = CASE id
            WHEN 1 THEN '[0,1]'
            WHEN 2 THEN '[1,2]'
            WHEN 3 THEN '3'
            WHEN 4 THEN '-1'
            WHEN 5 THEN 'true'
            WHEN 6 THEN 'false'
            WHEN 7 THEN '[[1,6],[8,12]]'
        END
    """)

    # Explicitly tell PostgreSQL how to convert TEXT → JSON
    bind.exec_driver_sql("""
        ALTER TABLE test_cases
        ALTER COLUMN input_data TYPE JSON
        USING input_data::json
    """)

    bind.exec_driver_sql("""
        ALTER TABLE test_cases
        ALTER COLUMN expected_output TYPE JSON
        USING expected_output::json
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.alter_column('expected_output',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('input_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
