"""add hidden flag to test cases

Revision ID: aa87400e7c32
Revises: f322e333b287
Create Date: 2026-08-16 13:06:47.897068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa87400e7c32'
down_revision = 'f322e333b287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_column('is_hidden')

    # ### end Alembic commands ###
